unset PATH
export GEMPATH=/root/.gem/ruby/2.3.0/bin:$HOME/.gem/ruby/2.3.0/bin
export GOROOT=/usr/lib/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin
export JVM_HOME=/usr/lib/jvm
export JAVA_HOME=$JVM_HOME/default/bin:$JVM_HOME/java-8-openjdk/bin
export PERL_PATH=/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
export PATH=/usr/local/bin:/usr/lib/hardening-wrapper/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:$GOPATH/bin:$GOROOT/bin:$GEMPATH:$PERL_PATH:$JAVA_HOME
